### PR TITLE
Remove unnecessary 'using TourOfCsharp;' from HelloWorld.cs (fixes #46250)

### LINKED ISSUE #46250: bug in code sample
### Type of issue

Code doesn't work

### Description

```
using System;
using TourOfCsharp; // unknown namespace, not needed

class Program
{
    static void Main()
    {
        // This line prints "Hello, World" 
        Console.WriteLine("Hello, World");
    }
}
```

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/overview

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/tour-of-csharp/overview.md

### Document Version Independent Id

ffae9ae1-d3f5-4192-0a18-ca475c712813

### Platform Id

41a669fb-55ed-d212-8af3-4d212ac707a2

### Article author

@BillWagner

### Metadata

* ID: 85b00578-37d2-1fd1-911d-3097aa73f212
* PlatformId: 41a669fb-55ed-d212-8af3-4d212ac707a2 
* Service: **dotnet-csharp**
* Sub-service: **get-started**

### PR DESCRIPTION
**Pull request by yufeih**
This PR removes the unnecessary and incorrect `using TourOfCsharp;` directive from the `HelloWorld.cs` code sample, as reported in issue #46250. The directive referenced a non-existent namespace and could cause confusion for readers.

### CODE REVIEW

File: docs/csharp/tour-of-csharp/snippets/shared/HelloWorld.cs [hunk 1]
```diff
@@ -1,5 +1,4 @@
 ﻿using System;
```
Comment (BillWagner) [inline docs/csharp/tour-of-csharp/snippets/shared/HelloWorld.cs:1]: This should have been a namespace declaration, rather than a `using` statement:

```suggestion
﻿using System;
﻿namespace TourOfCsharp;
```

**Review by BillWagner — APPROVED** [review]
Thanks @yufeih 

I'll ship this, but I want a different fix to declare a namespace, which is what many samples will show.
