### PR TITLE
Fix samples

### LINKED ISSUE #29224: Code comments refer to incorrect method name
The example in the https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref#passing-an-argument-by-reference-an-example section refers to "Main" in a few places, but actually that's not the name of the method in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d
* Version Independent ID: 4f413bcc-90e7-d971-fe75-b4876124e75d
* Content: [ref keyword - C# Reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref)
* Content Source: [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/ref.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #42499: First example missing usage example of passing a parameter by ref.
### Type of issue

Missing information

### Description

The first bullet says:
> In a method signature and in a method call, to pass an argument to a method [by reference](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/method-parameters#ref-parameter-modifier).

But the following example doesn't show passing a parameter by `ref`. The logic in the example is right and shows how a struct value will *not* change if passed by value, but an example showing how to pass a parameter by `ref` would probably be more helpful.

Perhaps adding a method like:
```cs
static void TakeStructByRef(ref TheStruct s)
{
    s.willIChange = "Changed";
}
```

Would be useful.

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/keywords/ref.md

### Document Version Independent Id

4f413bcc-90e7-d971-fe75-b4876124e75d

### Article author

@BillWagner

### Metadata

* ID: 3d67349b-72bc-b7cf-f754-fa62d1fb592d 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 320285](https://dev.azure.com/msft-skilling/Content/_workitems/edit/320285)

### PR DESCRIPTION
**Pull request by BillWagner**
Over time, the samples used in this article (many of which were also used in other articles) drifted from their original purpose.

Put those samples in this article only, and make them as small as possible to demonstrate the syntax for disambiguation purposes.

Fixes #42499
Fixes #29224

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/csharp/language-reference/keywords/ref.md](https://github.com/dotnet/docs/blob/8a207a858820e11c58c98116479bc5914e202a84/docs/csharp/language-reference/keywords/ref.md) | [docs/csharp/language-reference/keywords/ref](https://review.learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/ref?branch=pr-en-us-42842) |

### CODE REVIEW

File: docs/csharp/language-reference/keywords/snippets/refkeyword.cs [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+    }
+    // </PassByReference>
+
+    // <ReturnByReference>
+    public ref int RefMax(ref int left, ref int right)
+    {
+        if (left > right)
+        {
+            return ref left;
+        } else
```
Comment (IEvangelist) [inline docs/csharp/language-reference/keywords/snippets/refkeyword.cs:16]:
```suggestion
        }
        else
```

**Review by IEvangelist — APPROVED** [review]
