### PR TITLE
Fix resources

### LINKED ISSUE #23433: How to write C# analyzer code fix is inconsistent in its message in documentation and the example code
The documentation is out-of-sync with the example code.  The documentation states to make the AnalyzerMessageFormat:

Variable '{0}' can be made constant

When later issuing the diagnostic, the code is:

context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation()));

Note that no argument is passed to Diagnostic.Create to substitute for the {0} in the format string.

If I look at the example code in GitHub (https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/tutorials/snippets/how-to-write-csharp-analyzer-code-fix/MakeConst/MakeConst/MakeConstAnalyzer.cs#ReportDiagnostic) the associated resource file in that project has the AnalyzerMessageFormat as:

can be made constant

I think the right approach is to change the example code's resource to actually take the variable name as an argument and update the Diagnostic.Create call to issue the diagnostic as:

context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation(), variable.Identifier));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e3fc905-7aa1-7f5e-9bfe-fbcef461ad5e
* Version Independent ID: a286e20b-1e43-dc57-e0fb-5a9dee7ec3f6
* Content: [Tutorial: Write your first analyzer and code fix](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix?source=docs)
* Content Source: [docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md](https://github.com/dotnet/docs/blob/main/docs/csharp/roslyn-sdk/tutorials/how-to-write-csharp-analyzer-code-fix.md)
* Product: **dotnet-csharp**
* Technology: **csharp-roslyn**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #23433

### CODE REVIEW

File: docs/csharp/roslyn-sdk/tutorials/snippets/how-to-write-csharp-analyzer-code-fix/MakeConst/MakeConst/MakeConstAnalyzer.cs [hunk 1]
```diff
@@ -118,7 +118,7 @@ private void AnalyzeNode(SyntaxNodeAnalysisContext context)
             }
 
             // <SnippetReportDiagnostic>
-            context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation()));
+            context.ReportDiagnostic(Diagnostic.Create(Rule, context.Node.GetLocation(), localDeclaration.Declaration.Variables.First().Identifier.ValueText));
```
Comment (Youssef1313) [inline docs/csharp/roslyn-sdk/tutorials/snippets/how-to-write-csharp-analyzer-code-fix/MakeConst/MakeConst/MakeConstAnalyzer.cs:121]: @BillWagner @sharwell In case of multiple variables, e.g: `int x = 0, y = 0;`, the message will have the first name only. I assume it's acceptable, but wanted to explicitly note about that.

File: docs/csharp/roslyn-sdk/tutorials/snippets/how-to-write-csharp-analyzer-code-fix/MakeConst/MakeConst/Resources.resx [hunk 2]
```diff
@@ -118,15 +118,15 @@
...
     <comment>An optional longer localizable description of the diagnostic.</comment>
   </data>
   <data name="AnalyzerMessageFormat" xml:space="preserve">
-    <value>can be made constant</value>
+    <value>Variable '{0}' can be made constant</value>
     <comment>The format-able message the diagnostic displays.</comment>
   </data>
   <data name="AnalyzerTitle" xml:space="preserve">
-    <value>Variable can be made constant.</value>
+    <value>Variable can be made constant</value>
```
Comment (Youssef1313) [inline docs/csharp/roslyn-sdk/tutorials/snippets/how-to-write-csharp-analyzer-code-fix/MakeConst/MakeConst/Resources.resx:129]: The `.` at the end is intentionally removed here. Only the description should end with a period.

**Review by BillWagner — APPROVED** [review]
Thanks for making this update @Youssef1313 

I'll :shipit: now.
