### PR TITLE
Provide workaround for lack of DataTable support

### LINKED ISSUE #21366: JsonSerializer.Parse<DataTable> failed
Convert an object into json string and then convert into DataTable is an easy way to generate `DataTable`, but this approach fails in `dotnet core 3 preview5`

I have created a working dotnet core 2 code snippet at [https://dotnetfiddle.net/cD6NFD](https://dotnetfiddle.net/cD6NFD)

dotnetfiddle doesn't support dotnet core 3 yet, so my dotnet core 3 code example see below:

```csharp
using System.Data;
using System.Text.Json.Serialization;

public class UserDetails
{
    public string Id { get; set; }
    public string Name { get; set; }
    public string City { get; set; }
    public string Country { get; set; }
}

List<UserDetails> persons = new List<UserDetails>()
{
    new UserDetails() {Id="1001", Name="ABCD", City ="City1", Country="USA"},
    new UserDetails() {Id="1002", Name="PQRS", City ="City2", Country="INDIA"},
    new UserDetails() {Id="1003", Name="XYZZ", City ="City3", Country="CHINA"},
    new UserDetails() {Id="1004", Name="LMNO", City ="City4", Country="UK"},
};
var table = JsonSerializer.Parse<DataTable>(JsonSerializer.ToString(persons));
```

below are the error log:
```
CLR/System.Text.Json.JsonReaderException 'The JSON value from [System.Data.DataTable] could not be converted to System.Object.'
```

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #21366 

Will change snippet link to a permalink in a new PR after this PR is merged.

Internal review URLs
* https://review.docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?branch=pr-en-us-24669
* https://review.docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?branch=pr-en-us-24669
* https://review.docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-supported-collection-types?branch=pr-en-us-24669

Code file:
* https://github.com/tdykstra/dotnet-docs/blob/datatable/docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs

### CODE REVIEW

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 1]
```diff
@@ -0,0 +1,248 @@
...
+                                }
+                                break;
+                            default:
+                                jsonWriter.WriteString(key, valueString);
+                                break;
+                        }
+                    }
+                    jsonWriter.WriteEndObject();
+                }
+            }
```
Comment (IEvangelist) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:139]:
```suggestion
            jsonWriter.WriteStartArray();
            foreach (DataRow dr in value.Rows)
            {
                jsonWriter.WriteStartObject();
                foreach (DataColumn col in value.Columns)
                {
                    var key = col.ColumnName.Trim();
                    var valueString = dr[col].ToString();
                    switch (col.DataType.FullName)
                    {
                        case "System.Guid":
                            jsonWriter.WriteString(key, valueString);
                            break;
                        case "System.Char":
                        case "System.String":
                            jsonWriter.WriteString(key, valueString);
                            break;
                        case "System.Boolean":
                            Boolean.TryParse(valueString, out bool boolValue);
                            jsonWriter.WriteBoolean(key, boolValue);
                            break;
                        case "System.DateTime":
                            if (DateTime.TryParse(valueString, out DateTime dateValue))
                            {
                                jsonWriter.WriteString(key, dateValue);
                            }
                            else
                            {
                                jsonWriter.WriteString(key, "");
                            }
                            break;
                        case "System.TimeSpan":
                            if (DateTime.TryParse(valueString, out DateTime timeSpanValue))
                            {
                                jsonWriter.WriteString(key, timeSpanValue.ToString());
                            }
                            else
                            {
                                jsonWriter.WriteString(key, "");
                            }
                            break;
                        case "System.Byte":
                        case "System.SByte":
                        case "System.Decimal":
                        case "System.Double":
                        case "System.Single":
                        case "System.Int16":
                        case "System.Int32":
                        case "System.Int64":
                        case "System.UInt16":
                        case "System.UInt32":
                        case "System.UInt64":
                            if (long.TryParse(valueString, out long intValue))
                            {
                                jsonWriter.WriteNumber(key, intValue);
                            }
                            else
                            {
                                double.TryParse(valueString, out double doubleValue);
                                jsonWriter.WriteNumber(key, doubleValue);
                            }
                            break;
                        default:
                            jsonWriter.WriteString(key, valueString);
                            break;
                    }
                }
                jsonWriter.WriteEndObject();
            }
```

Remove extra scope `{` and `}`

**Review by IEvangelist — APPROVED** [review]

**Comment by tdykstra** [comment]
Thanks for the review, @IEvangelist !

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 2]
```diff
@@ -0,0 +1,246 @@
...
+                }
+                Console.WriteLine();
+            }
+
+            // Serialize the DataTable and display the JSON
+            var serializeOptions = new JsonSerializerOptions();
+            serializeOptions.WriteIndented = true;
+            serializeOptions.Converters.Add(new DataTableJsonConverter());
+            jsonString = JsonSerializer.Serialize(weatherForecasts, serializeOptions);
+            Console.WriteLine(jsonString);
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:53]: Do we show the output anywhere?

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 3]
```diff
@@ -0,0 +1,246 @@
...
+            {
+                jsonWriter.WriteStartObject();
+                foreach (DataColumn col in value.Columns)
+                {
+                    var key = col.ColumnName.Trim();
+                    var valueString = dr[col].ToString();
+                    switch (col.DataType.FullName)
+                    {
+                        case "System.Guid":
+                            jsonWriter.WriteString(key, valueString);
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:80]: Can we do a test to see if leveraging `Utf8JsonWriter` support for all these primitive types is more performant? Similar to the work you did with our guidance on reusing `JsonSerializerOptions` instances, we can use `StopWatch` to check elapsed time (and [Process.PrivateMemorySize64](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.privatememorysize64?view=net-5.0#System_Diagnostics_Process_PrivateMemorySize64)) to check allocations. We'd do this here and for all types below.

```suggestion
                            jsonWriter.WriteString(key, (Guid)dr[col]);
```

Rather than convert to a string, we unbox the primitive type and use the native writer support directly.

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 4]
```diff
@@ -0,0 +1,246 @@
...
+            jsonWriter.WriteEndArray();
+        }
+    }
+    public static class Extensions
+    {
+        public static DataTable JsonElementToDataTable(this JsonElement dataRoot)
+        {
+            var dataTable = new DataTable();
+            var firstPass = true;
+            foreach (var element in dataRoot.EnumerateArray())
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:147]: nit: use type name instead of `var` since it isn't stated on the RHS (here and elsewhere).

Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:147]: nit: new line

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 5]
```diff
@@ -0,0 +1,246 @@
...
+                if (firstPass)
+                {
+                    foreach (var col in element.EnumerateObject())
+                    {
+                        var colValue = col.Value;
+                        dataTable.Columns.Add(new DataColumn(col.Name, colValue.ValueKind.ValueKindToType(colValue.ToString())));
+                    }
+                    firstPass = false;
+                }
+                var row = dataTable.NewRow();
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:158]: nit: new line

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 6]
```diff
@@ -0,0 +1,246 @@
...
+                foreach (var col in element.EnumerateObject())
+                {
+                    row[col.Name] = col.Value.JsonElementToTypedValue();
+                }
+                dataTable.Rows.Add(row);
+            }
+            return dataTable;
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:165]: nit: new line

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 7]
```diff
@@ -0,0 +1,246 @@
...
+                    }
+                    else
+                    {
+                        return typeof(System.Double);
+                    }
+                case JsonValueKind.True:        // 5
+                case JsonValueKind.False:       // 6
+                    return typeof(System.Boolean);
+                case JsonValueKind.Undefined:   // 0
+                    return null;
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:187]: What happens when `null` is returned here?

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 8]
```diff
@@ -0,0 +1,246 @@
...
+                dataTable.Rows.Add(row);
+            }
+            return dataTable;
+        }
+
+        private static Type ValueKindToType(this JsonValueKind valueKind, string value)
+        {
+            switch (valueKind)
+            {
+                case JsonValueKind.String:      // 3
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:172]: What do these commented numbers mean?

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 9]
```diff
@@ -0,0 +1,246 @@
...
+                default:
+                    return typeof(System.Object);
+            }
+        }
+
+        private static object JsonElementToTypedValue(this JsonElement jsonElement)
+        {
+            switch (jsonElement.ValueKind)
+            {
+                case JsonValueKind.Object:      // 1  (these need special handling)?
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:203]: nit: separate these cases since they have different behavior.

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 10]
```diff
@@ -0,0 +1,246 @@
...
+                            if (datetime.Kind == DateTimeKind.Local)
+                            {
+                                if (jsonElement.TryGetDateTimeOffset(out DateTimeOffset datetimeOffset))
+                                {
+                                    return datetimeOffset;
+                                }
+                            }
+                            return datetime;
+                        }
+                        return jsonElement.ToString();
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:224]: What's the behavior for arrays and object? I think it's better to throw `NotSupportedException` and let users decide when they fork our example (I'd also do this anywhere it's not clear what the expected behavior should be).

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 9 above)
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:203]: ditto: what do the numbers mean?

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs [hunk 11]
```diff
@@ -0,0 +1,246 @@
...
+                {
+                    foreach (var col in element.EnumerateObject())
+                    {
+                        var colValue = col.Value;
+                        dataTable.Columns.Add(new DataColumn(col.Name, colValue.ValueKind.ValueKindToType(colValue.ToString())));
+                    }
+                    firstPass = false;
+                }
+                var row = dataTable.NewRow();
+                foreach (var col in element.EnumerateObject())
```
Comment (layomia) [inline docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:159]: Can we refactor this logic so that we don't loop through `element.EnumerateObject()` two times on the first past?

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 8 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:172]: The integer value of JsonValueKind.  I'll remove the comments.

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 7 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:187]: ArgumentNullException in dataTable.Columns.Add

I'll change this to throw a NotSupportedException here

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 9 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:203]: >separate these cases since they have different behavior.

and throw NotSupportedException for them?

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 2 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs:51]: I added sample output to the end of the file.

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 3 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs]: I tried Utf8JsonWriter support for primitive types and tested with 1,000,000 rows in the table -- result was lower allocations (MemorySize64 1,306M vs. 1,316M) but more elapsed time (952 vs. 877). I left the new code in place.

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 8 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs]: Enum values, I'm removing the comments.

File: docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs (hunk 9 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-how-to/csharp/RoundtripDataTable.cs]: enum values, I'm removing the comments

**Review by layomia — APPROVED** [review]
LGTM
