### PR TITLE
Fix IsApproximatelyEqual sample for negative values

### LINKED ISSUE #9173: Downloaded PDF bookmarks links are wrong
When I click Download PDF, the generated file has a list of bookmarks, which point to inadequate places in document.
Contents table has no links at all.
Problem exists in .NET guides and ASP.NET Core

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d49bc05d-7c8e-5f89-aac5-d133225da4d5
* Version Independent ID: 2f831fc9-dfe6-15db-4ec6-00f59c2dacc2
* Content: [.NET Core Guide](https://docs.microsoft.com/en-us/dotnet/core/)
* Content Source: [docs/core/index.md](https://github.com/dotnet/docs/blob/master/docs/core/index.md)
* Product: **dotnet-core**
* GitHub Login: @richlander
* Microsoft Alias: **mairaw**

### LINKED ISSUE #9173: Example `IsApproximatelyEqual` has a bug when using negative numbers
The example code for `IsApproximatelyEqual` in [single](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Single.xml) fails when you pass it negative numbers.

For example:
```c#
IsApproximatelyEqual(-10, -0.1)
```

returns `True`

This seems to be caused by the `divisor` being negative:

```c#
double divisor = Math.Max(value1.Value, value2.Value);
if (divisor.Equals(0))
{
    divisor = Math.Min(value1.Value, value2.Value);
}

return Math.Abs(value1.Value - value2.Value) / divisor <= epsilon;
```

Given two negative numbers the divisor is negative and so always `<= epsilon`. Testing locally a fix is to `Math.Abs(divisor)` or change the return line to:

```c#
return Math.Abs((value1.Value - value2.Value) / divisor) <= epsilon;
```

### PR DESCRIPTION
**Pull request by cycopepe**
## Fix IsApproximatelyEqual sample for negative values

Example for runtime-library/system-single related to IsApproximatelyEqual is wrong for negative values. [see published page here](https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-single)

Changes includes fixed on IsApproximatelyEqual methods and adding example case using negative values

Fixes  [9173](https://github.com/dotnet/dotnet-api-docs/issues/9173)

### CODE REVIEW

**Comment by cycopepe** [comment]
#sign-off

File: docs/fundamentals/runtime-libraries/snippets/System/Single/Overview/csharp/comparison4.cs [hunk 1]
```diff
@@ -14,6 +14,12 @@ public static void Main()
         Console.WriteLine("{0:R} is approximately equal to {1:R}: {2}",
                           one1, one2,
                           IsApproximatelyEqual(one1, one2, .000001f));
+        
+        float negativeOne1 = -1 * one1;
+        float negativeOne2 = -1 * one2;
+        Console.WriteLine("{0:R} is approximately equal to {1:R}: {2}",
+                            negativeOne1, negativeOne2,
+                            IsApproximatelyEqual(negativeOne1, negativeOne2, .000001f));
```
Comment (gewarren) [inline docs/fundamentals/runtime-libraries/snippets/System/Single/Overview/csharp/comparison4.cs:22]:
```suggestion

Console.WriteLine($"{negativeOne1:R} = {negativeOne2:R}: {negativeOne1.Equals(negativeOne2)}");
Console.WriteLine($"{negativeOne1:R} is approximately equal to {negativeOne2:R}: " +
    $"{IsApproximatelyEqual(negativeOne1, negativeOne2, .000001f)}");
```

**Review by gewarren — APPROVED** [review]
Thanks @cycopepe
