### PR TITLE
Edit pass and updates for Nullable Analysis attributes

### LINKED ISSUE #25069: Attributes for null-state static analysis | The sample
From [Attributes for null-state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

```csharp
bool TryGetMessage(string key, out string message)
{
    message = "";
    return true;
}
```
> If the TryGetMessage method returns true, the value of message isn't null. If the return value is false, the value of message (and its null state) is null.

1. Sample does not contain any execution branch that demonstrates `false`/`null` result.
2. It is not truth at all.

Let model the sample in here.

```csharp
#nullable enable
static bool TryGetMessage ( string key, out string message )
{
  if ( key == string.Empty )
  {
    message = "";
    return true;
  }

  message = null; // Warning	CS8625	Cannot convert null literal to non-nullable reference type.
  return false;
}
#nullable disable
``` 
I did not find relevant specification or proposal but it seems natural that  `nullable annotation` of `out` parameter type denotes contract. Thus `null` cannot be assigned to `message`.

---

>(and its null state) is null.

The _null state_ has 2 options: `not null` and `maybe null`. `null` state does not exist.

---

>The rule for `key` can be expressed by the variable type: `key` should be a non-nullable reference type. The `message` parameter is more complex. It allows `null` as the argument, but guarantees, on success, that `out` argument isn't null. For these scenarios, you need a richer vocabulary to describe the expectations.

Missing `?` nullable annotation on `out string message` does not denote not `null` result on success. It denotes not `null` result no matter the return value if it even exists.

```csharp
#nullable enable
static bool IsDefault<T> ( T value , out string message )
where T : class
{
  if ( value is default(T) )
  {
    message = "Yes, sure!";
    return true;
  }

  message = "Sorry, no, it isn’t!";
  return false;
}
#nullable disable
```
---

> It allows `null` as the argument, but guarantees, on success, that `out` argument isn't null. 

Argument cannot be `null`. It is variable that is passed as `out` argument/parameter what has `null` value. One cannot simply code

```csharp
IsDefault (new object(), out string null);
// Error	CS1003	Syntax error, ',' expected
// Error	CS1525	Invalid expression term 'string'
```

It should be also clear what is **difference between** `argument` and `parameter`. Former resides at call site, latter in method signature.

---

>Once your code is _nullable aware_, those rules change. Reference types should never be the null value, and nullable reference types must be checked against null before being dereferenced.

It should be clear what is “_nullable aware_”? I guess it is `#nullable enable warnings`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #25071: Attributes for null-state static analysis| Attributes meaning overview
From [Attributes for null-state static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)

### Overview 

Attribute | Category | Meaning
-- | -- | --
AllowNull | Precondition | A non-nullable argument may be null.
DisallowNull | Precondition | A nullable argument should never be null.
MaybeNull | Postcondition | A non-nullable return value may be null.
NotNull | Postcondition | A nullable return value will never be null.
MaybeNullWhen | Conditional postcondition | A non-nullable argument may be null when the method returns the specified bool value.
NotNullWhen | Conditional postcondition | A nullable argument won't be null when the method returns the specified bool value.
NotNullIfNotNull | Conditional postcondition | A return value isn't null if the argument for the specified parameter isn't null.
MemberNotNull | Constructor helper methods | The listed member won't be null when the method returns.
MemberNotNullWhen | Constructor helper methods | The listed member won't be null when the method returns the specified bool value.
DoesNotReturn | Unreachable code | A method never returns. In other words, it always throws an exception.
DoesNotReturnIf | Unreachable code | This method never returns if the associated bool parameter has the specified value.

### Attribute usage

This table lists `attributes` that has slightly incomplete description in _Meaning_ column as corroborates [AttributeTargets Enum](https://docs.microsoft.com/en-us/dotnet/api/system.attributetargets?view=net-5.0) for each of them.

Attribute | AttributeTargets
-- | -- 
[`AllowNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.allownullattribute?view=net-5.0) | `Field` &#124; `Parameter` &#124; `Property`
[`DisallowNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.disallownullattribute?view=net-5.0) | `Field` &#124; `Parameter` &#124; `Property`
[`MaybeNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.maybenullattribute?view=net-5.0) | `Field` &#124; `Parameter` &#124; `Property` &#124; `ReturnValue`
[`NotNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullattribute?view=net-5.0) |  `Field` &#124; `Parameter` &#124; `Property` &#124; `ReturnValue`
[`NotNullIfNotNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullifnotnullattribute?view=net-5.0) | `Parameter` &#124; `Property` &#124; `ReturnValue`
[`MemberNotNull`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullattribute?view=net-5.0)  | `Method` &#124; `Property`
[`MemberNotNullWhen`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.membernotnullwhenattribute?view=net-5.0) | `Method` &#124; `Property`
---

1. Using terminologically exact term `argument` (in impossible context) should be avoided. `Attribute` can be applied only to `parameter` (method signature) as one can sense ouf of `AttributeTargets.Parameter` value.  It is impossible to apply `attribute` on `argument` (calling site).
2. [`DoesNotReturnAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnattribute?view=net-5.0) is not limited to always throwing methods.

```csharp
[DoesNotReturn]
public void BeReadingFromNetworkInterface ()
{
  while ( true )
  {
     // Never breaks and ends with application domain.
  }
}
```
The same applies to [DoesNotReturnIfAttribute ](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.doesnotreturnifattribute?view=net-5.0).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #25078: Postconditions: MaybeNull and NotNull | `T?` can be used as return type
From [Postconditions: MaybeNull and NotNull](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)

> You can't specify that the return value is `T?`. The method returns `null` when the sought item isn't found. Since you can't declare a `T?` return type, you add the `MaybeNull` annotation to the method return:

This is similar to #24980 – see https://github.com/dotnet/docs/issues/24980#issuecomment-873421206.

There should be likely something like _Since you should evade using T? in unconstrained methods …_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#summary)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #25209: Postconditions: `MaybeNull` and `NotNull` – `MaybeNull` usage example has little sense
From [Postconditions: MaybeNull and NotNull](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)

```C#
[return: MaybeNull]
public T Find<T>(IEnumerable<T> sequence, Func<T, bool> predicate)
```

> The preceding code informs callers that the contract implies a non-nullable type, but the return value may actually be null. Use the `MaybeNull` attribute when your API should be a non-nullable type, typically a generic type parameter, but there may be instances where `null` would be returned.

This example **implies** nothing about `nullability`.

```csharp
#nullable enable      
public T Find<T> ( IEnumerable<T> sequence, Func<T, bool> predicate ) => default;

void Seek ()
{
  object? x = Find<object?> (Array.Empty<object?> (), _ => true);
  object x1 = Find<object> (Array.Empty<object> (), _ => true);
  int? x2 = Find<int?> (Array.Empty<int?> (), _ => true);
  int x3 = Find<int> (Array.Empty<int> (), _ => true);
}  
#nullable disable
```
Examples show that any kind of `nullability` works with `Find<T>` method.

---

In fact, from usage perspective for generics there is no difference between `T?` `return type` and `[return: MaybeNull]`. (There are different metadata.). This applies (also) to any `reference type`. That, since `?` in generic method declaration is understood as `reference type` `nullable annotation`.

```csharp
[return: MaybeNull] public T Find<T> ( ) => default;
public T? Find2<T> () => default;    
public T Find3<T> ( ) => default;  // Warning	CS8603	Possible null reference return.

void Test ()
{
  object x = Find<object> (); // Warning	CS8600	Converting null literal or possible null value to non-nullable type.
  object x2 = Find2<object> (); // Warning	CS8600	Converting null literal or possible null value to non-nullable type.
  object x3 = Find3<object> ();
}
```
---

Maybe this should not be much about method `declaration` but rather about its `implementation`. I guess that paragraph is about to recommend `[return: MaybeNull]` in order to avoid confusion around `T?` as return type. 

```c#
public T ReturnDefault1<T> () => default; // Warning	CS8603	Possible null reference return.
[return: MaybeNull] public T ReturnDefault2<T> () => default; // Ok
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #25210: Conditional post-conditions: `NotNullWhen`, `MaybeNullWhen`, and `NotNullIfNotNull` – TryGetMessage sample is wrong
From [Conditional post-conditions: `NotNullWhen`, `MaybeNullWhen`, and `NotNullIfNotNull`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#conditional-post-conditions-notnullwhen-maybenullwhen-and-notnullifnotnull)

```c#
bool TryGetMessage(string key, out string message)
{
  message = "";
  return true;
}
```
> If the method returns true, the value of message isn't null; otherwise, the method sets message to null.

This example repeats same misconception as described in #25069, i.e. `message` `parameter` declared as `out string message` cannot be set to `null` in `#nullable enable` context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #25211: Conditional post-conditions: `NotNullWhen`, `MaybeNullWhen`, and `NotNullIfNotNull` – `reference type` `nullable annotation` is not part of `method signature`
From [Conditional post-conditions: `NotNullWhen`, `MaybeNullWhen`, and `NotNullIfNotNull`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#conditional-post-conditions-notnullwhen-maybenullwhen-and-notnullifnotnull)

>  When you update the signature for nullable reference types, make `message` a `string?` and add an attribute:

`Annotation` by definition is not part of `signature declaration`. Beside terminology it works like this also in real.

```c#
#nullable enable
class SignatureTestClass
{
  void SignatureTestMethod ( object? obj ) { }
  void SignatureTestMethod ( object obj ) { } // Error CS0111 Type 'SignatureTestClass' already defines a member called 'SignatureTestMethod' with the same parameter types
}
#nullable disable
```
Sample shows that `nullable annotated` `reference type` is not recognized as `method overload`; it is not recognized as different `signature`.

Same applies to attributes.
```c#
bool SignatureTestMethod2 ( object obj ) => default;
bool SignatureTestMethod2 ( [NotNullWhen(true)] object obj ) => default; // Error CS0111 Type 'SignatureTestClass' already defines a member called 'SignatureTestMethod2' with the same parameter types
```
---

It is `method declaration` what is subject to update.

---
#### Other occurences

- >If the `url` argument isn't null, the output isn't `null`. Once nullable references are enabled, that signature works correctly, provided your API never accepts a null argument. However, if the argument could be null, then return value could also be null. You could change the signature to the following code:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #25332: `DoesNotReturnAttribute` – missing warning in unreachable code path
From [Verify unreachable code](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#verify-unreachable-code)

> The compiler helps you in three ways. First, the compiler issues a warning if there's a path where the method can exit without throwing an exception. Second, the compiler marks any code after a call to that method as unreachable, until an appropriate catch clause is found. Third, the unreachable code won't affect any null states. Consider this method:

```c#
[DoesNotReturn]
private void FailFast()
{
    throw new InvalidOperationException();
}

public void SetState(object containedField)
{
    if (!isInitialized)
    {
        FailFast();
    }

    // unreachable code:
    _field = containedField;
}
```

- Such noted `// unreachable code:` is not inevitably unreachable. This is depends on `if (!isInitialized)` execution selection which is unpredictable in this sample.
- I tried to verify 2nd case 
> Second, the compiler marks any code after a call to that method as unreachable, until an appropriate catch clause is found.

but it seems either documentation is wrong or compiler has some issue.

```c#
class UnreachableCodeTests
{
  object _field = new ();
  
  [DoesNotReturn]
  private static void FailFast () => throw new InvalidOperationException ();
  
  public void SetState ( object containedField )
  {      
    if ( DateTime.Now.Minute % 3 == 0)
    {
      FailFast ();
      _field = containedField; // NO ISSUE HERE‼
    }
        
    _field = new string(_field.ToString());
  }
}
```

### Sample project attached.
[DoesNotReturnTests.zip](https://github.com/dotnet/docs/files/6872841/DoesNotReturnTests.zip)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ae1afa1-7c5f-862b-08f9-23cf5928953e
* Version Independent ID: 9ae2922b-5108-ed50-768b-30f08cc3fc30
* Content: [C# Reserved attributes: Nullable static analysis](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/nullable-analysis#postconditions-maybenull-and-notnull)
* Content Source: [docs/csharp/language-reference/attributes/nullable-analysis.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/attributes/nullable-analysis.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by BillWagner**
First, perform a general edit. The general edit includes an update to how `T` and `T?` are interpreted for nullable and non-nullable value types and reference types with and without constraints.

Then, address the following issues:

Fixes #25332

For this issue, update the descriptions of `DoesNotReturn` and `DoesNotReturnIf` attributes. The scope of the warnings was trimmed from the spec for the initial previews.

Fixes #25211

Don't use "signature" to describe type annotation changes.

Fixes #25210
Fixes #25069

Update sample and tighten language on `out` arguments.

Fixes #25078
Fixes #25209

Further edits on generics, `MaybeNull` and `NotNull` attributes.

Fixes #25071 

Update the overview description. I did not update the samples to include an infinite loop, as described in the issue. While true, that's more of a sidetrip

### CODE REVIEW

File: docs/csharp/language-reference/attributes/snippets/NewPropertyOrFieldAttribute.cs [hunk 1]
```diff
@@ -12,11 +12,11 @@ class MyClass
     {
         // Attribute attached to property:
         [NewPropertyOrField]
-        public string Name { get; set; }
+        public string Name { get; set; } = string.Empty;
 
         // Attribute attached to backing field:
         [field:NewPropertyOrField]
```
Comment (IEvangelist) [inline docs/csharp/language-reference/attributes/snippets/NewPropertyOrFieldAttribute.cs:18]:
```suggestion
        [field: NewPropertyOrField]
```

File: docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs [hunk 2]
```diff
@@ -10,11 +10,15 @@ namespace attributes
 #nullable disable
     public class NullableOblivious
     {
+        private Dictionary<string, string> messageMap = new ();
```
Comment (IEvangelist) [inline docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs:13]:
```suggestion
        private Dictionary<string, string> _messageMap = new();
```

File: docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs [hunk 3]
```diff
@@ -10,11 +10,15 @@ namespace attributes
...
         // <TryGetExample>
         bool TryGetMessage(string key, out string message)
         {
-            message = "";
-            return true;
+            if (messageMap.ContainsKey(key))
```
Comment (IEvangelist) [inline docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs:17]:
```suggestion
            if (_messageMap.ContainsKey(key))
```

File: docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs [hunk 4]
```diff
@@ -67,12 +71,16 @@ string GetTopLevelDomainFromFullUrl(string url)
...
     public class NullableAttributes
     {
+        private Dictionary<string, string> messageMap = new();
 
         // <NotNullWhenTryGet>
         bool TryGetMessage(string key, [NotNullWhen(true)] out string? message)
         {
-            message = "";
-            return true;
+            if (messageMap.ContainsKey(key))
```
Comment (IEvangelist) [inline docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs:79]:
```suggestion
            if (_messageMap.ContainsKey(key))
```

File: docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs [hunk 5]
```diff
@@ -67,12 +71,16 @@ string GetTopLevelDomainFromFullUrl(string url)
 #nullable restore
     public class NullableAttributes
     {
+        private Dictionary<string, string> messageMap = new();
```
Comment (IEvangelist) [inline docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs:74]:
```suggestion
        private Dictionary<string, string> _messageMap = new();
```

File: docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs [hunk 6]
```diff
@@ -147,33 +158,31 @@ private void FailFast()
...
             }
         }
 
-        public void SetFieldState(object containedField)
+        public void SetFieldState(object? containedField)
         {
-            FailFastIf(isInitialized);
-
-            // unreachable code when "isInitialized" is false:
+            FailFastIf(containedField==null);
```
Comment (IEvangelist) [inline docs/csharp/language-reference/attributes/snippets/NullableAttributes.cs:184]:
```suggestion
            FailFastIf(containedField == null);
```

**Review by IEvangelist — APPROVED** [review]
Just a few nits, but otherwise :shipit: - great work, and now I feel like I need to start doing a better job using the appropriate attributes in my code to help ensure the correct intent is understood by the compiler.
