### PR TITLE
JsonSerializerOptions with JsonNode or JsonDocument

### LINKED ISSUE #27824: JsonIgnoreCondition.WhenWritingNull is not work as my expect when Serialize a JsonDocument
### Description

I Serialize a JsonDocument with setting JsonIgnoreCondition.WhenWritingNull ，but it not work,

SDK: net 6
OS: MacOS

### Reproduction Steps

This is my Demo Code

```C#
// See https://aka.ms/new-console-template for more information

using System.Text.Json;
using System.Text.Json.Serialization;


Person person = new Person();

var personJsonStr = System.Text.Json.JsonSerializer.Serialize(person);

Console.WriteLine(personJsonStr);

var jsonDocument = System.Text.Json.JsonSerializer.Deserialize<JsonDocument>(personJsonStr);

JsonSerializerOptions options = new JsonSerializerOptions()
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
};

var jsonStr = JsonSerializer.Serialize(jsonDocument, options);

Console.WriteLine(jsonStr);

public class Person
{
    public int Age { get; set; }
    
    public Address Address { get; set; }
}

public class Address
{
    public string Location { get; set; }
}
```

### Expected behavior

jsonStr does not contain null value,

### Actual behavior

jsonStr =>  "{\"Age\":0,\"Address\":null}"

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #27824 

Related to https://github.com/dotnet/runtime/issues/54184

File Type | File Name | Published Url
-- | -- | --
Content | docs/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter.md | https://review.docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter?branch=pr-en-us-28853

### CODE REVIEW

File: docs/standard/serialization/snippets/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter/csharp/JsonDocumentWithJsonSerializerOptions.cs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+        // Serialize and ignore null properties - null Address property is omitted
+        // Output: {"Name":"Nancy"}
+        JsonSerializerOptions options = new()
+        {
+            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
+        };
+        string personJson = JsonSerializer.Serialize(person, options);
+        Console.WriteLine(personJson);
+
+        // Default serialization - Address property included with null token.
```
Comment (eiriktsarpalis) [inline docs/standard/serialization/snippets/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter/csharp/JsonDocumentWithJsonSerializerOptions.cs:23]: Would it make sense to show the default behavior first?

**Review by eiriktsarpalis — APPROVED** [review]
LGTM, thanks.

File: docs/standard/serialization/snippets/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter/csharp/JsonDocumentWithJsonSerializerOptions.cs (hunk 1 above)
Comment (tdykstra) [reply docs/standard/serialization/snippets/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter/csharp/JsonDocumentWithJsonSerializerOptions.cs:23]: Sorry, missed this comment earlier. Yes it does, I'll change it.
