### PR TITLE
Fix two small issues

### LINKED ISSUE #30357: "record" variable marked as keyword in samples, making them unnecessarily hard to understand
The syntax highlighting is making the example using a variable named "record" very confusing. It took me a while to realize that wasn't some mind bending new fancy switch statement, but just switching on the variable "record". And I've been coding C# for a decade.  Probably best to choose a different variable name to avoid confusing the syntax highlighter... these new features are hard enough to parse as is, without the added complication of incorrectly marking things as keywords that aren't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0
* Version Independent ID: 312e9c81-ee2a-1d84-64d7-bcaa71d7eab8
* Content: [Patterns - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns#list-patterns)
* Content Source: [docs/csharp/language-reference/operators/patterns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #30411: DEPOSIT/WITHDRAWL example is missing a minus sign
The following line
`[_, "FEE", var fee]               => decimal.Parse(fee),`
should read
`[_, "FEE", var fee]               => -decimal.Parse(fee),`

as fees are deducted from the balance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9112c305-f1cd-1aa5-4557-2c7d757e6ca0
* Version Independent ID: 312e9c81-ee2a-1d84-64d7-bcaa71d7eab8
* Content: [Patterns - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/patterns)
* Content Source: [docs/csharp/language-reference/operators/patterns.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/operators/patterns.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by BillWagner**
Fixes #30411 - Fix switch expression unary sign.
Fixes #30357 - Change variable name from `record` to `transaction`

### CODE REVIEW

File: docs/csharp/language-reference/operators/snippets/patterns/ListPattern.cs [hunk 1]
```diff
@@ -56,17 +56,17 @@ public static void Examples()
...
         {
-            balance += record switch
+            balance += transaction switch
             {
                 [_, "DEPOSIT", _, var amount]     => decimal.Parse(amount),
                 [_, "WITHDRAWAL", .., var amount] => -decimal.Parse(amount),
                 [_, "INTEREST", var amount]       => decimal.Parse(amount),
-                [_, "FEE", var fee]               => decimal.Parse(fee),
+                [_, "FEE", var fee]               => -decimal.Parse(fee),
                 _                                 => throw new InvalidOperationException($"Record {record} is not in the expected format!"),
```
Comment (BillWagner) [inline docs/csharp/language-reference/operators/snippets/patterns/ListPattern.cs:67]:
```suggestion
                _                                 => throw new InvalidOperationException($"Record {transaction} is not in the expected format!"),
```

**Review by IEvangelist — APPROVED** [review]
