### PR TITLE
Fix struct example

### LINKED ISSUE #9972: IEquatable should not be used on both parent and child
IEquatable should not be used on both the parent and child class definitions. This will lead to nasty results, and bugs for clients. For example, if we define pointE as (3, 4, 6), now all of a sudden pointE equals any other compile time 2D point with (3, 4) as the first two coordinates, if pointE's compile time type is 2D point.

IEquatable should only be used on child, sealed classes so that polymorphism will work as expected for equality definitions. Please correct me if this is a misunderstanding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95b738e-a319-8947-c098-692068c24b9c
* Version Independent ID: 227a6999-9add-4a0a-98cb-c0c6624d6089
* Content: [How to: Define Value Equality for a Type - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### LINKED ISSUE #20015: Errors in the struct example
Hi

I believe there are some errors in the code example for structs (struct TwoDPoint):

1)
In the ctor x is assigned to both X and Y.

2)
The implementation of GetHashCode is simply "return X ^ Y;". This will produce the same hash code when X and Y are swapped which (unless X == Y) is wrong and inconsistent with the behaviour of Equals.
In the class examples this problem is solved by multiplying either component by a fixed number (e.g. "return X * 0x00010000 + Y;") which will probaly work fine in practice. Though, it might in theory produce some bad results due to possible overflows. Alternatively, one could bitwise rotate either X or Y by a number of bits.

It might actually be helpful to highlight the problem of "combining hash codes into one properly" in the article. My suspicion is that this is a very common mistake; I've seen it many times. Also it can cause some nasty bugs...

Other than that, I think the article is very helpful!

Thanks,
Jonas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e95b738e-a319-8947-c098-692068c24b9c
* Version Independent ID: 227a6999-9add-4a0a-98cb-c0c6624d6089
* Content: [How to define value equality for a type - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type)
* Content Source: [docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md)
* Product: **dotnet-csharp**
* Technology: **csharp-fundamentals**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by tdykstra**
Fixes #20015
Fixes #9972 

There's no diff on the code because I created new files. I’m fixing error number 2 in #20015 by adding the class example’s constructor validation to the struct, ensuring that x and y are  between 1 and 2000. The struct code can then adopt the class example’s hash override of `return X * 0x00010000 + Y;` in the struct without the possibility of overflow. There is no change to the class example code.

The Snippets 5000 error is because I added "no longer in use" comments to the struct and class examples in ~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideStatements/CS/Statements.cs, which doesn't have a project file.

### CODE REVIEW

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+        // Readonly auto-implemented properties.
+        public int X { get; private set; }
+        public int Y { get; private set; }
+
+        // Set the properties in the constructor.
+        public TwoDPoint(int x, int y)
+        {
+            if ((x < 1) || (x > 2000) || (y < 1) || (y > 2000))
+            {
+                throw new System.ArgumentException("Point must be in range 1 - 2000");
```
Comment (Youssef1313) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:15]: Is `System.` extra

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 2]
```diff
@@ -0,0 +1,202 @@
...
+    class TwoDPoint : IEquatable<TwoDPoint>
+    {
+        // Readonly auto-implemented properties.
+        public int X { get; private set; }
+        public int Y { get; private set; }
+
+        // Set the properties in the constructor.
+        public TwoDPoint(int x, int y)
+        {
+            if ((x < 1) || (x > 2000) || (y < 1) || (y > 2000))
```
Comment (Youssef1313) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:13]: not very important, but this could benefit from pattern combinators. Something like:

```csharp
if (x is (< 1 or > 2000) || y is (< 1 or > 2000))
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 3]
```diff
@@ -0,0 +1,202 @@
...
+
+        public override bool Equals(object obj)
+        {
+            return this.Equals(obj as TwoDPoint);
+        }
+
+        public bool Equals(TwoDPoint p)
+        {
+            // If parameter is null, return false.
+            if (Object.ReferenceEquals(p, null))
```
Comment (Youssef1313) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:29]: `p is null`?

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+
+            // Return true if the fields match.
+            // Note that the base class is not invoked because it is
+            // System.Object, which defines Equals as reference equality.
+            return (X == p.X) && (Y == p.Y);
+        }
+
+        public override int GetHashCode()
+        {
+            return X * 0x00010000 + Y;
```
Comment (Youssef1313) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:54]: `HashCode.Combine`?

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+    class ThreeDPoint : TwoDPoint, IEquatable<ThreeDPoint>
+    {
+        public int Z { get; private set; }
+
+        public ThreeDPoint(int x, int y, int z)
+            : base(x, y)
+        {
+            if ((z < 1) || (z > 2000))
+            {
+                throw new System.ArgumentException("Point must be in range 1 - 2000");
```
Comment (Youssef1313) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:91]: Extra `System.`?

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs (hunk 4 above)
Comment (pkulikov) [reply docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:54]: or just `(X, Y).GetHashCode()`

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 6]
```diff
@@ -0,0 +1,202 @@
+﻿namespace ValueEqualityClass
+{
+    using System;
+    class TwoDPoint : IEquatable<TwoDPoint>
+    {
+        // Readonly auto-implemented properties.
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:6]: I see that the code has been just moved without major updates, so I'm feeling free to suggest to remove all the obvious, won't-be-localized comments. Moreover, this comment is even wrong, as the properties are not readonly, as they can be modified not only by the constructor, but also by the type methods.

```suggestion
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 7]
```diff
@@ -0,0 +1,202 @@
...
+        public int X { get; private set; }
+        public int Y { get; private set; }
+
+        // Set the properties in the constructor.
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:10]:
```suggestion
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 8]
```diff
@@ -0,0 +1,202 @@
...
+        }
+
+        public override bool Equals(object obj)
+        {
+            return this.Equals(obj as TwoDPoint);
+        }
+
+        public bool Equals(TwoDPoint p)
+        {
+            // If parameter is null, return false.
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:28]:
```suggestion
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 9]
```diff
@@ -0,0 +1,202 @@
...
+                return false;
+            }
+            // Equals handles case of null on right side.
+            return lhs.Equals(rhs);
+        }
+
+        public static bool operator !=(TwoDPoint lhs, TwoDPoint rhs)
+        {
+            return !(lhs == rhs);
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:78]:
```suggestion
        public static bool operator !=(TwoDPoint lhs, TwoDPoint rhs) => !(lhs == rhs);
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 10]
```diff
@@ -0,0 +1,202 @@
...
+            {
+                throw new System.ArgumentException("Point must be in range 1 - 2000");
+            }
+            this.Z = z;
+        }
+
+        public override bool Equals(object obj)
+        {
+            return this.Equals(obj as ThreeDPoint);
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:99]:
```suggestion
        public override bool Equals(object obj) => this.Equals(obj as ThreeDPoint);
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 11]
```diff
@@ -0,0 +1,202 @@
...
+            else
+            {
+                return false;
+            }
+        }
+
+        public override int GetHashCode()
+        {
+            return (X * 0x100000) + (Y * 0x1000) + Z;
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:131]:
```suggestion
        public override int GetHashCode() => (X, Y, Z).GetHashCode();
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 12]
```diff
@@ -0,0 +1,202 @@
...
+
+        public static bool operator ==(ThreeDPoint lhs, ThreeDPoint rhs)
+        {
+            // Check for null.
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:135]:
```suggestion
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs [hunk 13]
```diff
@@ -0,0 +1,202 @@
...
+                return false;
+            }
+            // Equals handles the case of null on right side.
+            return lhs.Equals(rhs);
+        }
+
+        public static bool operator !=(ThreeDPoint lhs, ThreeDPoint rhs)
+        {
+            return !(lhs == rhs);
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs:154]:
```suggestion
        public static bool operator !=(ThreeDPoint lhs, ThreeDPoint rhs) => !(lhs == rhs);
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs [hunk 14]
```diff
@@ -0,0 +1,120 @@
+﻿namespace ValueEqualityStruct
+{
+    using System;
+    struct TwoDPoint : IEquatable<TwoDPoint>
+    {
+        // Read/write auto-implemented properties.
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs:6]:
```suggestion
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs [hunk 15]
```diff
@@ -0,0 +1,120 @@
...
+        }
+
+        public override bool Equals(object obj)
+        {
+            if (obj is TwoDPoint)
+            {
+                return this.Equals((TwoDPoint)obj);
+            }
+            return false;
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs:28]:
```suggestion
        public override bool Equals(object obj) => obj is TwoDPoint other && this.Equals(other);
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs [hunk 16]
```diff
@@ -0,0 +1,120 @@
...
+
+        public bool Equals(TwoDPoint p)
+        {
+            return (X == p.X) && (Y == p.Y);
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs:33]:
```suggestion
        public bool Equals(TwoDPoint p) => X == p.X && Y == p.Y;
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs [hunk 17]
```diff
@@ -0,0 +1,120 @@
...
+
+        public override int GetHashCode()
+        {
+            return X * 0x00010000 + Y;
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs:38]:
```suggestion
        public override int GetHashCode() => (X, Y).GetHashCode();
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs [hunk 18]
```diff
@@ -0,0 +1,120 @@
...
+
+        public static bool operator ==(TwoDPoint lhs, TwoDPoint rhs)
+        {
+            return lhs.Equals(rhs);
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs:43]:
```suggestion
        public static bool operator ==(TwoDPoint lhs, TwoDPoint rhs) => lhs.Equals(rhs);
```

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs [hunk 19]
```diff
@@ -0,0 +1,120 @@
...
+
+        public static bool operator !=(TwoDPoint lhs, TwoDPoint rhs)
+        {
+            return !(lhs.Equals(rhs));
+        }
```
Comment (pkulikov) [inline docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityStruct/Program.cs:48]:
```suggestion
        public static bool operator !=(TwoDPoint lhs, TwoDPoint rhs) => !(lhs == rhs);
```

**Review by pkulikov — COMMENTED** [review]
That should make code snippets occupy less space on screen

File: docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs (hunk 4 above)
Comment (Youssef1313) [reply docs/csharp/programming-guide/statements-expressions-operators/snippets/how-to-define-value-equality-for-a-type/ValueEqualityClass/Program.cs]: > or just `(X, Y).GetHashCode()`

Wow! That looks very neat ❤️

File: docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md [hunk 20]
```diff
@@ -12,27 +12,31 @@ ms.assetid: 4084581e-b931-498b-9534-cf7ef5b68690
...
+When you define a [record](../classes-and-structs/records.md), the compiler automatically implements value equality. When you define a class or struct, you decide whether it makes sense to create a custom definition of value equality (or equivalence) for the type. Typically, you implement value equality when you expect to add objects of the type to a collection, or when their primary purpose is to store a set of fields or properties. You can base your definition of value equality on a comparison of all the fields and properties in the type, or you can base the definition on a subset.
```
Comment (BillWagner) [inline docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md:15]: I'm wondering if this should be stronger:

```suggestion
[Records](../classes-and-structs/records.md), the compiler automatically implement value equality. Consider defining a `record` instead of a `class` when your type models data and should implement value equality. When you define a class or struct, you decide whether it makes sense to create a custom definition of value equality (or equivalence) for the type. Typically, you implement value equality when you expect to add objects of the type to a collection, or when their primary purpose is to store a set of fields or properties. You can base your definition of value equality on a comparison of all the fields and properties in the type, or you can base the definition on a subset.
```

**Review by BillWagner — APPROVED** [review]
This is a great set of updates @tdykstra 

I had one suggestion. I wonder if we want to emphasize that a `record` implements value equality for you. In general, I think that's a major reason for choosing a `record` over a `class`. 

I'm ambivalent about the wording, but see what you think.

File: docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md (hunk 20 above)
Comment (tdykstra) [reply docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md]: I made a few small changes, does this revision look good to you?

Comment (BillWagner) [reply docs/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type.md]: I really like that @tdykstra That's perfect.
