### PR TITLE
Revert collection expression for Try.nET

### LINKED ISSUE #40755: The code example for foreach does not work
### Type of issue

Code doesn't work

### Description

[Enter feedback here]
The Code example of foreach statement with list of fibonaci numbers does not work.
The list need to be initialized differently : 
Instead of: `List<int> fibNumbers = [0, 1, 1, 2, 3, 5, 8, 13];`
It should be: `List<int> fibNumbers = new List<int> {0, 1, 1, 2, 3, 5, 8, 13};`

### Page URL

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/statements/iteration-statements#code-try-6

### Content source URL

https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/statements/iteration-statements.md

### Document Version Independent Id

8b6cb66c-8bef-fed0-1677-acee6bd3e052

### Article author

@BillWagner

### Metadata

* ID: 23685290-d092-48ee-f7d9-e2c2bdc86a18 
* Service: **dotnet-csharp**
* Sub-service: **lang-reference**

---
[Associated WorkItem - 252999](https://dev.azure.com/msft-skilling/Content/_workitems/edit/252999)

### PR DESCRIPTION
**Pull request by BillWagner**
This snippet runs in the TRY.NET editor, so collection expressions are supported yet.

Fixes #40755

### CODE REVIEW

File: docs/csharp/language-reference/statements/snippets/iteration-statements/ForeachStatement.cs [hunk 1]
```diff
@@ -12,7 +12,7 @@ public static void Examples()
     private static void ForeachWithIEnumerable()
     {
         // <WithIEnumerable>
-        List<int> fibNumbers = [0, 1, 1, 2, 3, 5, 8, 13];
+        List<int> fibNumbers = { 0, 1, 1, 2, 3, 5, 8, 13 };
```
Comment (IEvangelist) [inline docs/csharp/language-reference/statements/snippets/iteration-statements/ForeachStatement.cs:15]:
```suggestion
        List<int> fibNumbers = new() { 0, 1, 1, 2, 3, 5, 8, 13 };
```

**Review by IEvangelist — APPROVED** [review]
LGTM, just need to fix the minor compile error.
