### PR TITLE
fix: dotnet/docs#18900, code example now compliant

### LINKED ISSUE #18900: Code example not compliant with guideline
Page says:

> Do not use implicit typing to determine the type of the loop variable in foreach loops.
> 
> The following example uses explicit typing in a foreach statement.
> 
> ```
> foreach (var ch in laugh)
> {
>    if (ch == 'h')
> ...
> ```

The first line of the code example should read `foreach (char ch in laugh)` according to the guideline text right above it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a3c147e-2271-4d7c-712b-2f705b5ecbc5
* Version Independent ID: 2c1a7cfe-364e-408e-77c1-9fae2b0da643
* Content: [C# Coding Conventions - C# Programming Guide](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions)
* Content Source: [docs/csharp/programming-guide/inside-a-program/coding-conventions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/inside-a-program/coding-conventions.md)
* Product: **dotnet-csharp**
* Technology: **csharp-get-started**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by kthy**
## Summary

Sample code for `foreach` now uses explicit type instead of var, as per the guideline.

Fixes #18900.

### CODE REVIEW

File: samples/snippets/csharp/VS_Snippets_VBCSharp/csprogguidecodingconventions/cs/program.cs [hunk 1]
```diff
@@ -102,7 +102,9 @@ static void Main(string[] args)
             //</snippet11>
 
             //<snippet12>
-            foreach (var ch in laugh)
+            // Do not use implicit typing to determine the type of the loop
+            // variable in foreach loops.
```
Comment (IEvangelist) [inline samples/snippets/csharp/VS_Snippets_VBCSharp/csprogguidecodingconventions/cs/program.cs:106]:
```suggestion
```
Please remove the comments.  I'm fine with the explicit typing by, no need to comment it.

**Review by IEvangelist — CHANGES_REQUESTED** [review]
This looks good, thank you. We'll :shipit: when you make the suggested changes.

File: samples/snippets/csharp/VS_Snippets_VBCSharp/csprogguidecodingconventions/cs/program.cs (hunk 1 above)
Comment (BillWagner) [reply samples/snippets/csharp/VS_Snippets_VBCSharp/csprogguidecodingconventions/cs/program.cs:106]: Some additional context on the comments: We limit comments in our samples because comment text is not localized. For that reason we prefer explanatory text in the accompanying article.

Comment (kthy) [reply samples/snippets/csharp/VS_Snippets_VBCSharp/csprogguidecodingconventions/cs/program.cs]: Aight, was just emulating the samples above in the code file. :) The explanatory text is already in the doc.

**Review by BillWagner — APPROVED** [review]
This LGTM.

I'll :shipit: now.

Thanks @kthy for making this fix.

**Comment by BillWagner** [comment]
@IEvangelist Can you approve and ship this? The changes have been made.

**Review by IEvangelist — APPROVED** [review]
Looks good to me, we'll :shipit: - thank you 🙏
