### PR TITLE
fix extra braces in example

### LINKED ISSUE #29121: C#11 interpolated string example using wrong number of braces
In one of the C#11 code examples using triple quotes, there are too many braces around the x and y part of the coordinate.

```
var pointMessage = $$"""The point {{{X}}}, {{{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";
...
// output:  The point {2, 3} is 3.605551275463989 from the origin.
```
should be
`var pointMessage = $$"""The point {{{X}}, {{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0665571-35b7-0841-5719-b69456b35cfb
* Version Independent ID: 0410420b-3b12-6d96-40cf-56f22ac19a1d
* Content: [$ - string interpolation - C# reference](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)
* Content Source: [docs/csharp/language-reference/tokens/interpolated.md](https://github.com/dotnet/docs/blob/main/docs/csharp/language-reference/tokens/interpolated.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @pkulikov
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by BillWagner**
Fixes #29121

### CODE REVIEW

File: docs/csharp/language-reference/tokens/snippets/string-interpolation.cs [hunk 1]
```diff
@@ -121,8 +121,8 @@ private static void InterpolatedRawLiteralStringsWithBraces()
         int X = 2;
         int Y = 3;
 
-        var pointMessage = $$"""The point {{{X}}}, {{{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";
-
+        var pointMessage = $$"""The point {{{X}}, {{Y}}} is {{Math.Sqrt(X * X + Y * Y)}} from the origin""";
+
```
Comment (IEvangelist) [inline docs/csharp/language-reference/tokens/snippets/string-interpolation.cs:125]:
```suggestion

```

**Review by IEvangelist — APPROVED** [review]
