### PR TITLE
Fix 22180

### LINKED ISSUE #22180: Incorrect example output on page.
The commented output of the second example of continuation with child tasks (detached) is incorrect.
The example shows the following output: (which seems to be just copied by mistake from the previous example)

// The example displays the similar output:
//     Running antecedent task 1...
//     Launching attached child tasks...
//     Finished launching detached child tasks...
//        Attached child task #2 running
//        Attached child task #3 running
//        Attached child task #1 running
//        Attached child task #4 running
//        Attached child task #5 running
//     Executing continuation of Task 1

**While the correct output should be:**

Running antecedent task 1...
Launching attached child tasks...
Finished launching detached child tasks...
Executing continuation of Task 1
   Attached child task #1 running
   Attached child task #4 running
   Attached child task #2 running
   Attached child task #3 running
   Attached child task #5 running

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be073b14-6d0b-60be-7dff-4674bcb6c674
* Version Independent ID: a5fa3e78-73de-3360-1253-00545a2b4ef2
* Content: [Chaining tasks using continuation tasks](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks)
* Content Source: [docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md](https://github.com/dotnet/docs/blob/master/docs/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

### PR DESCRIPTION
**Pull request by IEvangelist**
## Summary

Verified the output was [incorrect here](https://dotnetfiddle.net/5WHAgn).

Fixes #22180

## Preview

✔️  [Chaining tasks using continuation tasks](https://review.docs.microsoft.com/en-us/dotnet/standard/parallel-programming/chaining-tasks-by-using-continuation-tasks?branch=pr-en-us-22253)

### CODE REVIEW

File: docs/standard/parallel-programming/snippets/cs/detached1.cs [hunk 1]
```diff
@@ -38,9 +38,9 @@ public static async Task Main()
...
 //     Finished launching detached child tasks...
+//     Executing continuation of Task 1
+//        Attached child task #1 running
+//        Attached child task #5 running
 //        Attached child task #2 running
 //        Attached child task #3 running
-//        Attached child task #1 running
 //        Attached child task #4 running
-//        Attached child task #5 running
-//     Executing continuation of Task 1
```
Comment (Youssef1313) [inline docs/standard/parallel-programming/snippets/cs/detached1.cs:46]: The output order is non-deterministic. Each run can produce a different output.
That's why the comment before the output says that it produces "**similar**" output.
Instead of changing the order, which doesn't solve the issue, I'd emphasize the fact that the order is non-deterministic, possibly with technical reasoning about why this is happening.

**Comment by BillWagner** [comment]
@IEvangelist 

The comment by @Youssef1313 is correct. The order of tasks finishing is not guaranteed in this sample. This change isn't necessary, and the related issue can be closed.

File: docs/standard/parallel-programming/snippets/cs/detached1.cs (hunk 1 above)
Comment (IEvangelist) [reply docs/standard/parallel-programming/snippets/cs/detached1.cs:46]: > @IEvangelist David Pine FTE
> 
> The comment by @Youssef1313 is correct. The order of tasks finishing is not guaranteed in this sample. This change isn't necessary, and the related issue can be closed.

Yes, the numbered tasks are non-deterministic. This fix was to re-order the "Executing continuation of Task 1" which is guaranteed before the numbered tasks.  It was incorrectly at the bottom before - which is wrong.

Comment (BillWagner) [reply docs/standard/parallel-programming/snippets/cs/detached1.cs:46]: Got it. Thanks.

**Review by BillWagner — APPROVED** [review]
This LGTM @IEvangelist 

You can :shipit: when ready.
