### PR TITLE
Corrected exception handling

### LINKED ISSUE #6442: TestCatch2()
When sw is null, this line (in the finally block) will produce an unhandled exception :
sw.Close();

It happens when there is no c:\test directory.

Furthermore, if c:\test does exist but there is no c:\test\test.txt file, this file will be created anyway.
So I don't see why we would want to catch a FileNotFoundException.
I would suggest:
1. to replace the FileNotFoundException with DirectoryNotFoundException
2. to add in the finally block, this line of code to avoid the unhandled exception:
if (sw != null)
just before sw.Close();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b719792d-1f95-6743-743a-8906fe08e764
* Version Independent ID: f67c914a-a895-2fd4-5b5a-2f5bedde1f91
* Content: [Using Exceptions (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/exceptions/using-exceptions)
* Content Source: [docs/csharp/programming-guide/exceptions/using-exceptions.md](https://github.com/dotnet/docs/blob/master/docs/csharp/programming-guide/exceptions/using-exceptions.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

### PR DESCRIPTION
**Pull request by rpetrusha**
## Corrected exception handling

There are two problems with the original code:
- It throws a NullReferenceException if the StreamWriter cannot be instantiated because the file c://test/test.txt does not exist.
- It handles a FileNotFoundException but not a DirectoryNotFoundException. Either can be thrown.

I've wrapped the StreamWriter in a `using` statement and handled DirectoryNotFoundException.

Fixes #6442

### CODE REVIEW

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs [hunk 1]
```diff
@@ -1,27 +1,32 @@
...
+            static void Main()
             {
-                sw = new System.IO.StreamWriter(@"C:\test\test.txt");
-                sw.WriteLine("Hello");
-            }
+                try
+                {
+                    using(var sw = new StreamWriter(@"C:\test\test.txt"))
+                    {
+                    sw.WriteLine("Hello");
```
Comment (jzeferino) [inline docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: This line should be indented to the right.

**Review by jzeferino — CHANGES_REQUESTED** [review]
LGTM. Only one minor indentation issue.

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs (hunk 1 above)
Comment (rpetrusha) [reply docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: Thanks for catching that, @jzeferino!

**Review by jzeferino — APPROVED** [review]
LGTM now.

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs [hunk 2]
```diff
@@ -1,27 +1,32 @@
...
+                {
+                    using(var sw = new StreamWriter(@"C:\test\test.txt"))
+                    {
+                       sw.WriteLine("Hello");
+                    }   
+                }
+                // Put the more specific exceptions first.
+                catch (DirectoryNotFoundException ex)
+                {
+                    System.Console.WriteLine(ex.ToString());
```
Comment (svick) [inline docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: There's `using System;` at the top, so just `Console.WriteLine` (without `System.`) can be used here.

Also, `.ToString()` is not necessary.

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs [hunk 3]
```diff
@@ -1,27 +1,32 @@
-        static void TestCatch2()
+        using System;
```
Comment (svick) [inline docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: Nit: why is the whole file indented?

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs [hunk 4]
```diff
@@ -1,27 +1,32 @@
...
-            System.IO.StreamWriter sw = null;
-            try
+            static void Main()
             {
-                sw = new System.IO.StreamWriter(@"C:\test\test.txt");
-                sw.WriteLine("Hello");
-            }
+                try
+                {
+                    using(var sw = new StreamWriter(@"C:\test\test.txt"))
```
Comment (svick) [inline docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: Nit: there's usually a space between `using` and the opening parenthesis.

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs [hunk 5]
```diff
@@ -1,27 +1,32 @@
-        static void TestCatch2()
+        using System;
+        using System.IO;
+
+        public class ExceptionExample
```
Comment (svick) [inline docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: Won't it look odd that most examples in the article will be snippets with a `TestThrow`/`TestCatch`/etc. method, while this example will be a full program with `ExceptionExample` class?

**Review by BillWagner — APPROVED** [review]
These changes make a much better example of production code. I've approved this, but it would be great if you address the indenting before merging.

File: docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs (hunk 5 above)
Comment (rpetrusha) [reply docs/csharp/programming-guide/exceptions/codesnippet/CSharp/using-exceptions_3.cs]: I think it does look odd, @svick. In fact, I find the code snippets somewhat odd -- without an entry point and invocation, they're not executable.  For new users (who are most likely to need to read this topic), I think that's confusing. I'll create an issue to standardize the code in this topic; what I really wanted to do here, though, was correct the exception handling.

**Comment by rpetrusha** [comment]
Thanks, @svick, for the thorough review! I hadn't even noticed the bizarre indentation.

**Comment by jzeferino** [comment]
@rpetrusha I guess you got the @ wrong.

**Comment by rpetrusha** [comment]
You're right, @jzeferino. Thanks for the review! I appreciate it.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.

**Comment by rpetrusha** [comment]
Closing and reopening to begin new build.
